language: rust
cache: cargo
dist: trusty
os:
  - linux
  - osx

# Run builds for all the supported trains
rust:
  - stable
  - nightly

# The main build
script:
  - cargo build
  - cargo build --examples
  - cargo test
  - if [ -f "target/x86_64-unknown-linux-musl/release/console" ]; then docker build -f scripts/docker/Dockerfile . ; else echo "Skipping Docker release."; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/21e1d3b0e2793934dc3f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
