language: rust
cache: cargo
dist: trusty
matrix:
  include:
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-musl
      addons:
        apt:
          packages: &musl_packages
          - musl
          - musl-dev
          - musl-tools
    - os: linux
      rust: stable
      env: TARGET=i686-unknown-linux-gnu
    - os: linux
      rust: stable
      env: TARGET=i686-unknown-linux-musl
      addons:
        apt:
          packages: *musl_packages
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin

#os:
#  - linux
#  - osx

# Run builds for all the supported trains
rust:
  - stable
  - nightly

# The main build
script:
  - cargo build
  - cargo build --examples
  - cargo test
  - BUILD_RELEASE="true" bash scripts/docker/build.sh

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/21e1d3b0e2793934dc3f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
