[package]
name = "datafusion"
description = "DataFusion is a SQL query parser, planner, and distributed query processing framework for Rust inspired by Apache Calcite and Apache Spark"
version = "0.2.2"
authors = ["Andy Grove <andygrove73@gmail.com>"]
homepage = "https://datafusion.rs"
keywords = [ "distributed", "query", "data", "processing", "sql" ]
repository = "https://github.com/andygrove/datafusion-rs"
license = "Apache-2.0"
include = [
    "src/**/*.rs",
    "Cargo.toml",
]

[lib]
name = "datafusion"
path = "src/lib.rs"

[[bin]]
name = "worker"
path = "src/bin/worker/main.rs"

[[bin]]
name = "console"
path = "src/bin/console/main.rs"

[dependencies]

# NOTE: this depends on a fork of arrow until some PRs are merged
arrow = { git = "https://github.com/andygrove/arrow", rev = "1bd49cd83ffb6651d05092f9fff8ef9e0df59d69" }

bytes = "0.4"
byteorder = "1"
csv = "1.0.0-beta.5"
futures = "0.1.18"
futures-timer = "0.1"
tokio-core = "0.1.2"
hyper = "0.11.2"
#serde_derive = "1.0"
#serde = "1.0"
#serde_json = "1.0"
rprompt = "1.0"
etcd = "0.8.0"
clap = "2.31.2"
uuid = { version = "0.6.0-beta", features = ["v5"] }
liner = "0.4.3"

[dev-dependencies]
criterion = "0.2.0"

[[bench]]
name = "dataframe_bench"
harness = false

[[bench]]
name = "sql_bench"
harness = false

[[bench]]
name = "filter_primitive"
harness = false

[[bench]]
name = "udf_udt"
harness = false
