[package]
name = "datafusion"
description = "DataFusion is a SQL parser, planner, and execution framework for Rust with support for CSV and Apache Parquet file formats"
version = "0.2.12"
authors = ["Andy Grove <andygrove73@gmail.com>"]
homepage = "https://datafusion.rs"
documentation = "https://datafusion.rs/docs/"
keywords = [ "distributed", "query", "data", "processing", "sql" ]
repository = "https://github.com/datafusion-rs/datafusion"
license = "Apache-2.0"
include = [
    "src/**/*.rs",
    "Cargo.toml",
]

[lib]
name = "datafusion"
path = "src/lib.rs"

[[bin]]
name = "worker"
path = "src/bin/worker/main.rs"

[[bin]]
name = "console"
path = "src/bin/console/main.rs"

[dependencies]
bytes = "0.4"
byteorder = "1"
fnv = "1.0.3"
csv = "1.0.0"
datafusion-arrow = "0.1.0-nightly-20180505"

#arrow = { path = "../arrow/rust" }

lazy_static = "1.0"
parquet = "0.2.0"
#parquet = { path = "../parquet-rs" }
#futures = "0.1.18"
#futures-timer = "0.1"
#tokio-core = "0.1.2"
#hyper = "0.11.2"
#serde_derive = "1.0"
#serde = "1.0"
#serde_json = "1.0"
#rprompt = "1.0"
#etcd = "0.8.0"
clap = "2.31.2"
#uuid = { version = "0.6.0-beta", features = ["v5"] }
liner = "0.4.3"

[dev-dependencies]
criterion = "0.2.0"

#[[bench]]
#name = "dataframe_bench"
#harness = false

#[[bench]]
#name = "sql_bench"
#harness = false

[[bench]]
name = "read_csv"
harness = false

#[[bench]]
#name = "filter_primitive"
#harness = false
#
#[[bench]]
#name = "udf_udt"
#harness = false
