version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run:
          name: Building Main Code
          command: sh scripts/circle/build.sh
      - run:
          name: Building Examples
          command: sh scripts/circle/build-examples.sh
      - run:
          name: Test Code
          command: sh scripts/circle/test.sh
#workflows:
#  version: 2
#  build_with_examples:
#    jobs:
#      - build_main_code
#      - build_examples
#      - test:
#        requires:
#          - build_main_code
